### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by rrshaban** [nasser/---#11]
Hello,

I have been looking for documenation and have been unable to find a "help" function or anything similar -- is this a maintained project?

Also, it might make sense to change the link from qlblang (which no longer exists) to the Heroku app.

**Comment by Almusamim** [comment]
Yes please provide documentations so we can play around with this 👍

**Comment by r1shavd** [comment]
سلام، خوشبختَم. اِسمِ مَن ریشَب داس.
So, basically I know Urdu and Farsi. But, have 0 knowledge about Arabic. So, would need a documentation or even a tutorial video for learning this awesome language. I am highly interested in writting programs in it 😃.
خُداحافِظ! ❤️

**Comment by nasser** [comment]
Updated the link on the repo to http://nas.sr/---/ which should work indefinitely.

I consider this project complete and as a result it is not maintained in any meaningful sense. I accomplished what I set out to do in 2013 and I prefer to leave it in its current state. The closest thing to documentation is the امثلة button on the REPL which gives you three examples to study.
