### ISSUE TITLE
Sanity check?

### ISSUE THREAD

**Issue by brendanberg** [nasser/---#2]
Is the عدم؟ conditional broken? The string inside primitives.js looks like it's using a latin question mark instead of an arabic one, and the latin ? causes the REPL to choke I think? (I'm working pretty much blind here...)

![Screen Shot 2013-01-09 at 12 38 12 AM](https://f.cloud.github.com/assets/185650/52657/cafac2ca-5a1e-11e2-97c2-9c66a9ace8db.png)

**Comment by nasser** [comment]
I was using the wrong quotation mark in primitives.js. Correct syntax is ((عدم؟ (عدم), although you will have to print it to see it (REPL doesn't echo returns yet).
